language: node_js
node_js:
  - "6"
services:
  - mongodb
before_script:
  - npm run seed
script:
  - npm test
after_success:
  - npm install codeclimate-test-reporter -g
  - npm run coverage
addons:
    code_climate:
        repo_token: 3821377a426736abd98afd88df949ce06e65a660b70421199f5b7151992d6467